use_frameworks!

platform :ios, '9.0'

target 'GeoJsonParser_Example' do
  pod 'GeoJsonParser', :path => '../'

  target 'GeoJsonParser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
